
version: '3.4'

# Default compose will create an ows image, with dev settings and connect to a local db
services:
  ows:
    image: geoscienceaustralia/dea-datakube-config:latest
    environment:
      # # Defaults are defined in .env file
      DB_HOSTNAME: postgres
      DB_USERNAME: opendatacube
      DB_PASSWORD: opendatacubepassword
      DB_DATABASE: opendatacube
      DB_PORT: 5432
      WMS_CONFIG_PATH: ${CFG_PATH_PREFIX}/${WMS_CONFIG_FILE}
      # # Path from the PYTHONPATH to the config object (default PYTHONPATH is /env)
      DATACUBE_OWS_CFG: ${DATACUBE_OWS_CFG}
      AWS_DEFAULT_REGION: ap-southeast-2
      PYTHONPATH: /env/config
    depends_on:
      - postgres
    volumes:
      - ${OWS_CFG_MOUNT}:${CFG_PATH_PREFIX}
      - ${OWS_INVENTORY_JSON}:/env/config/inventory.json
      - ./compare-cfg.sh:/env/config/compare-cfg.sh

  postgres:
    image: kartoza/postgis:13-3.1
    environment:
      - POSTGRES_DB=opendatacube
      - POSTGRES_PASSWORD=opendatacubepassword
      - POSTGRES_USER=opendatacube
    ports:
      - "5432:5432"
    restart: always
